name: TODO and comment check
on: push
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: TODO and commented out code checker
      uses: nickssmith/TODO_and_CommentedCode_Check@1.2
    
